### ISSUE TITLE
Install fail: sed: can't read s/APP_NAME/pollux-server/g: No such file or directory

### ISSUE THREAD

**Issue by buren** [Albin-trialbee/rails-setup#1]
I get an error running

``` bash
bash rails-setup/setup.bash my-app-name
```

`sed: can't read s/APP_NAME/my-app-name/g: No such file or directory`
### Full output

```
# Ignore all logfiles and tempfiles.
/log/*
!/log/.keep
/tmp
Adding pattern(s) to: .gitignore
... adding 'log/.keep'
sed: can't read s/APP_NAME/my-app-name/g: No such file or directory
```

**Comment by Albin-Willman** [comment]
Hmms, I can't reproduce this. Is no rails app generated at all?

I would expect the printout from bundler to happen before what you wrote as full output...

**Comment by buren** [comment]
I truncated the output. So bundler ran without errors

**Comment by buren** [comment]
A rails app was generated, though config/database.yml looked like this :

```
database: APP_NAME_development
```

It errors on `sed: can't read s/APP_NAME/my-app-name/g: No such file or directory`, could it be setup.bash:22?

What version of `sed` are you using?  I'm on the GNU sed, version 4.2.2 (not the version that ships with osx).

**Comment by Albin-Willman** [comment]
I think I use the default one.

It seems that the `-i` flag is used differently between mac os and gnu std versions of sed...

http://www.grymoire.com/Unix/Sed.html

**Comment by Albin-Willman** [comment]
I have updated the code. It still works on mac and according to stackoverflow and some docs it should work on gnu sed as well but this is not verified.

**Comment by Albin-Willman** [comment]
Confirmed :smile:
